language: swift
# os: osx
osx_image: xcode12.2
xcode_project: TravisCI.xcodeproj # path to your xcodeproj folder
xcode_scheme: TravisCI
xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone 12
